steps:
  # Use a single step with the official Node.js v20 image for all commands
  # This ensures all installed packages are available for subsequent commands
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npm run build
        npm run deploy
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'