steps:
  # Use the official Node.js v20 image for installation and building
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
  # Use the standard Google Cloud builder for deployment, which has Firebase tools
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'deploy']
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'